def special_char_replacement(special_char):
    match special_char:
        case 'À': 
            return '%C3%80'
        case 'Á': 
            return '%C3%81'
        case 'Â': 
            return '%C3%82'
        case 'Ã': 
            return '%C3%83'
        case 'Ä': 
            return '%C3%84'
        case 'Å': 
            return '%C3%85'
        case 'Æ': 
            return '%C3%86'
        case 'Ç': 
            return '%C3%87'
        case 'È': 
            return '%C3%88'
        case 'É': 
            return '%C3%89'
        case 'Ê': 
            return '%C3%8A'
        case 'Ë': 
            return '%C3%8B'
        case 'Ì': 
            return '%C3%8C'
        case 'Í': 
            return '%C3%8D'
        case 'Î': 
            return '%C3%8E'
        case 'Ï': 
            return '%C3%8F'
        case 'Ð': 
            return '%C3%90'
        case 'Ñ': 
            return '%C3%91'
        case 'Ò': 
            return '%C3%92'
        case 'Ó': 
            return '%C3%93'
        case 'Ô': 
            return '%C3%94'
        case 'Õ': 
            return '%C3%95'
        case 'Ö': 
            return '%C3%96'
        case '×': 
            return '%C3%97'
        case 'Ø': 
            return '%C3%98'
        case 'Ù': 
            return '%C3%99'
        case 'Ú': 
            return '%C3%9A'
        case 'Û': 
            return '%C3%9B'
        case 'Ü': 
            return '%C3%9C'
        case 'Ý': 
            return '%C3%9D'
        case 'Þ': 
            return '%C3%9E'
        case 'ß': 
            return 's'
        case 'à': 
            return '%C3%A0'
        case 'á': 
            return '%C3%A1'
        case 'â': 
            return '%C3%A2'
        case 'ã': 
            return '%C3%A3'
        case 'ä': 
            return '%C3%A4'
        case 'å': 
            return '%C3%A5'
        case 'æ': 
            return '%C3%A6'
        case 'ç': 
            return '%C3%A7'
        case 'è': 
            return '%C3%A8'
        case 'é': 
            return '%C3%A9'
        case 'ê': 
            return '%C3%AA'
        case 'ë': 
            return '%C3%AB'
        case 'ì': 
            return '%C3%AC'
        case 'í': 
            return '%C3%AD'
        case 'î': 
            return '%C3%AE'
        case 'ï': 
            return '%C3%AF'
        case 'ð': 
            return '%C3%B0'
        case 'ñ': 
            return '%C3%B1'
        case 'ò': 
            return '%C3%B2'
        case 'ó': 
            return '%C3%B3'
        case 'ô': 
            return '%C3%B4'
        case 'õ': 
            return '%C3%B5'
        case 'ö': 
            return '%C3%B6'
        case '÷': 
            return '%C3%B7'
        case 'ø': 
            return '%C3%B8'
        case 'ù': 
            return '%C3%B9'
        case 'ú': 
            return '%C3%BA'
        case 'û': 
            return '%C3%BB'
        case 'ü': 
            return '%C3%BC'
        case 'ý': 
            return '%C3%BD'
        case 'þ': 
            return '%C3%BE'
        case 'ÿ': 
            return '%C3%BF'
        case _:
            return None
